---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dotfile-secret
  namespace: default
spec:
  encryptedData:
    .secret-file: AgBVQLZBVuKwKQFGkT9AY9BF1JkM74gBdx2LFvvBCkPl2pkk7+Bu4s1GhXWz6WGsecTK3b3RpphuZnQ+vqG0fYe050zB9Ue9ooAamtvGCqQgzTjBxRD7tfn0qVrQ7gSnETYvR7lroFdWMWEtb48DxkqZrOmNuJpw7rYWrXFIJx1FIvD/RwR3/VuUhWb0lR8OQkvG7T4Nr2Y3U/HGqOJnNO8nL4u+5fGcHwm5JZPS0hP13cIHsGdNOBD6cmEWNA0cy2kkUEI+GFYe0f2QuKR2fKS+9LsD3QKZi7S2m8ajLJLiwQKb9qLd+YA6gE2MVjxlGOa2z3Tyk4JmKq0UfppIFwbu+4DRMGQulxaBSY67869G6FjVJVxX1Fpk4cKlAbpe6xdNrnzJVaMDLdNnUIXKiz4GqSkMRteg3zS2ImXbpre63JQoRpJIM6LzplgpnsYn4eg+fcQz3WE7WPUCETdiSEEvefoNLegBswWZaZI8Vn5gG8OQboa/91xnhplOYd7QRvCczpXXxHBveI+VPVGxbm51q3MjcBzppP9IKn0Gb2xaHu9kFgj49MJXJRKWbsk8egXb4niCiJkEv+OMJgD+zAOBGmdLTjHQFVbi/08JP27kn6lvLtwZk0pud0/Ev01S1uRFtSk5l66jQk7tI4tnPgYNUPfi/xWC77zlV8lPg79T/da2rIlOmoDUBzdPFsxOUkeQuHOWatHrDvc+VA==
  template:
    metadata:
      creationTimestamp: null
      name: dotfile-secret
      namespace: default
